### ISSUE TITLE
You can't scroll to see full text on the about page

### ISSUE THREAD

**Issue by Bee4Queer** [kevjin/are-you-detail-oriented#1]
![image](https://github.com/kevjin/are-you-detail-oriented/assets/81586710/67b2617e-0472-442f-a445-d1e995d3a991)

**Comment by kevjin** [comment]
oh that's interesting! are you using a tablet or laptop? (curious about the dimensions)

**Comment by kevjin** [comment]
should be fixed now! updated some margins 🤞

**Comment by Bee4Queer** [comment]
looks good! and btw, I was using a laptop, not that it matters now
